version: '3'
services:
  aivophp:
        container_name: aivo
        hostname: aivophp
        build:
          context: .
          dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/app
        volumes:
            - .:/var/www/html/app

  aivonginx:
      container_name: aivo_nginx
      hostname: aivonginx
      image: nginx:1.17
      restart: unless-stopped
      depends_on:
        - aivophp
      ports:
        - '${APP_PORT:-80}:80'
      volumes:
        - .:/var/www/html/app
        - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf
