version: '3'
services:
    aivo:
        container_name: aivo
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - aivo

networks:
      aivo:
        driver: bridge
